version: '2'
services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile-elasticsearch
    container_name: elasticsearch
    restart: on-failure:5
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    restart: on-failure:5
    ports:
      - "5601:5601"
    depends_on: ['elasticsearch']

volumes:
  esdata: {}
